apiVersion: v1
kind: Service
metadata:
  name: oats-backend-api
  labels:
    app: oats-backend-api
spec:
  type: NodePort
  selector:
    app: oats-backend-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
