apiVersion: v1
kind: Service
metadata:
  name: oats-backend-api
  labels:
    app: oats-backend-api
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: oats-backend-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oats-backend-api
  labels:
    app: oats-backend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oats-backend-api
  template:
    metadata:
      labels:
        app: oats-backend-api
    spec:
      serviceAccountName: oats-backend-api
      containers:
        - name: backend-api
          image: oats-backend-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: "INFO"
          envFrom:
            - secretRef:
                name: oats-api-secrets
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
