apiVersion: v1
kind: ServiceAccount
metadata:
  name: oats-job-creator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oats-job-manager-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oats-job-manager-binding
subjects:
  - kind: ServiceAccount
    name: oats-job-creator
roleRef:
  kind: Role
  name: oats-job-manager-role
  apiGroup: rbac.authorization.k8s.io