# infra/base/ui-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: oats-ui-service
spec:
  # This selector ensures the service routes traffic to pods with the 'app: oats-ui' label
  selector:
    app: oats-ui
  ports:
    - protocol: TCP
      port: 80       # The port the service will be available on inside the cluster
      targetPort: 80 # The port the container is listening on
  type: ClusterIP # Exposes the service only within the cluster